from typing import Any


class ResumeService:
    @staticmethod
    def extract_text(file_path: str) -> str:
        return "Dummy extracted text from resume placeholder"

    @staticmethod
    def parse_resume(file_path: str) -> dict[str, Any]:
        return {"parsed": True, "source": "placeholder"}

    @staticmethod
    def calculate_ats_score(text: str) -> int:
        return 82

    @staticmethod
    def calculate_match_percentage(ats_score: int, required_skills: str | None = None) -> int:
        return min(100, ats_score + 5)

    @staticmethod
    def extract_skills(text: str) -> list[str]:
        return ["Python", "FastAPI", "SQLAlchemy"]

    @staticmethod
    def generate_summary(text: str) -> str:
        return "This is a placeholder summary generated by the AI service layer."
