/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterProfileRouteImport } from './routes/recruiter.profile'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as RecruiterAuthRouteImport } from './routes/recruiter.auth'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateAuthRouteImport } from './routes/candidate.auth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterProfileRoute = RecruiterProfileRouteImport.update({
  id: '/recruiter/profile',
  path: '/recruiter/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/recruiter/dashboard',
  path: '/recruiter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterAuthRoute = RecruiterAuthRouteImport.update({
  id: '/recruiter/auth',
  path: '/recruiter/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAuthRoute = CandidateAuthRouteImport.update({
  id: '/candidate/auth',
  path: '/candidate/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/auth': typeof RecruiterAuthRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/profile': typeof RecruiterProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/auth': typeof RecruiterAuthRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/profile': typeof RecruiterProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/auth': typeof RecruiterAuthRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/profile': typeof RecruiterProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate/auth'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/recruiter/auth'
    | '/recruiter/dashboard'
    | '/recruiter/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate/auth'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/recruiter/auth'
    | '/recruiter/dashboard'
    | '/recruiter/profile'
  id:
    | '__root__'
    | '/'
    | '/candidate/auth'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/recruiter/auth'
    | '/recruiter/dashboard'
    | '/recruiter/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateAuthRoute: typeof CandidateAuthRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  RecruiterAuthRoute: typeof RecruiterAuthRoute
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterProfileRoute: typeof RecruiterProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/profile': {
      id: '/recruiter/profile'
      path: '/recruiter/profile'
      fullPath: '/recruiter/profile'
      preLoaderRoute: typeof RecruiterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/recruiter/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/auth': {
      id: '/recruiter/auth'
      path: '/recruiter/auth'
      fullPath: '/recruiter/auth'
      preLoaderRoute: typeof RecruiterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/auth': {
      id: '/candidate/auth'
      path: '/candidate/auth'
      fullPath: '/candidate/auth'
      preLoaderRoute: typeof CandidateAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateAuthRoute: CandidateAuthRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  RecruiterAuthRoute: RecruiterAuthRoute,
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterProfileRoute: RecruiterProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
